stages:
  - verify
  - build
  - test

cache:
  - key: gradle-cache
    paths:
      - .gradle/caches/
      - .gradle/notifications/
      - .gradle/wrapper/

# verify stage
checkstyle:
  stage: verify
  image: eclipse-temurin:17-jdk-jammy
  script:
    # - curl -s https://api.github.com/repos/checkstyle/checkstyle/releases/latest | grep -wo 'https.*jar' | wget -q -O ./checkstyle.jar -i -    # Latest release is broken
    - wget -q -O ./checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.7.0/checkstyle-10.7.0-all.jar    # So we manually specify previous version
    - java -jar ./checkstyle.jar src/ -c /google_checks.xml

# build stage
build-gradle:
  stage: build
  needs:
    - checkstyle
  image: eclipse-temurin:17-jdk-jammy
  script:
    - chmod +x ./gradlew
    - ./gradlew --gradle-user-home .gradle/ build
  artifacts:
    expire_in: 1 week
    paths:
      - build/libs/

# test stage
junit:
  stage: test
  needs:
    - build-gradle
  image: eclipse-temurin:17-jdk-jammy
  script:
    - chmod +x ./gradlew
    - ./gradlew --gradle-user-home .gradle/ test
  dependencies:
    - build-gradle
  artifacts:
    when: always
    reports:
      junit:
        - build/test-results/test/**/TEST-*.xml
